Revert "change prefix of segment classes to empty string"
This reverts commit 6f71a7065c10af08b209bf510e017ef54b3a0dc4.

Numeric class names break "make watch-and-refresh".

src/TcljcWrapper.java:63: error: cannot access 100
          var fnStart = tcljc.main.___.start();
                                      ^
  class file for tcljc.main.100 not found